### ISSUE TITLE
Need favicon

### ISSUE THREAD

**Issue by ashanan** [mattbaker/messagefrom2016#13]
We need a favicon...do we also need a logo?

**Comment by mattbaker** [comment]
Waiting on #17. I don't recall exactly how to create favicon `.ico` files, I know it involves some photoshop plugin? @deanarutherford may be able to help there.

**Comment by mattbaker** [comment]
![screen shot 2016-11-15 at 10 55 44 pm](https://cloud.githubusercontent.com/assets/55462/20335257/a9182464-ab86-11e6-99fe-d2a67586f31a.png)
