### ISSUE TITLE
Update meta tag logos

### ISSUE THREAD

**Issue by mattbaker** [mattbaker/messagefrom2016#18]
We may need multiple sizes, we should check the dimensions twitter and facebook are expecting.

Relies on #17

**Comment by deanarutherford** [comment]
Yeah, and if we smash it down real far we might need to make the strokes thinner so it doesn't turn into a glob. I'ma go grab some lunch and then get on that. I can look it up, but if you find out the dimensions before I get back, feel free to enable my laziness.

**Comment by mattbaker** [comment]
Could try this thing? http://realfavicongenerator.net/

**Comment by deanarutherford** [comment]
Neat! I did that thing. Did I get everything you need?

[favicons.zip](https://github.com/mattbaker/messagefrom2016/files/592845/favicons.zip)

<link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
<link rel="icon" type="image/png" href="/favicon-32x32.png" sizes="32x32">
<link rel="icon" type="image/png" href="/favicon-16x16.png" sizes="16x16">
<link rel="manifest" href="/manifest.json">
<link rel="mask-icon" href="/safari-pinned-tab.svg" color="#5bbad5">
<meta name="theme-color" content="#ffffff">

**Comment by deanarutherford** [comment]
<link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
<link rel="icon" type="image/png" href="/favicon-32x32.png" sizes="32x32">
<link rel="icon" type="image/png" href="/favicon-16x16.png" sizes="16x16">
<link rel="manifest" href="/manifest.json">
<link rel="mask-icon" href="/safari-pinned-tab.svg" color="#5bbad5">
<meta name="theme-color" content="#ffffff">

hey it ate my code

**Comment by mattbaker** [comment]
@deanarutherford — we're good!

![screen shot 2016-11-15 at 10 49 30 pm](https://cloud.githubusercontent.com/assets/55462/20335158/e12e7782-ab85-11e6-930a-14bb3928bf87.png)

![screen shot 2016-11-15 at 10 45 34 pm](https://cloud.githubusercontent.com/assets/55462/20335163/e68b12ee-ab85-11e6-96ce-8372d7e02ab6.png)
