### ISSUE TITLE
Confirmation email copy

### ISSUE THREAD

**Issue by mattbaker** [mattbaker/messagefrom2016#25]
Currently:

![screen shot 2016-11-15 at 11 39 43 pm](https://cloud.githubusercontent.com/assets/55462/20336046/f7b2ad46-ab8c-11e6-984f-734bb2502b1c.png)

Got anything more inspiring, @deanarutherford?

**Comment by deanarutherford** [comment]
How about:

Your Message from 2016 has been saved. Click _here_ to confirm your email address so we can send your message to your future self.

**Comment by deanarutherford** [comment]
(and like the word here is the link)
