### ISSUE TITLE
Landing page after clicking confirmation link?

### ISSUE THREAD

**Issue by deanarutherford** [mattbaker/messagefrom2016#28]
Hi fellas,
Ignore me if I'm getting ahead of you/myself, but I just ran through the site (it's so almost a site! woo!) and thought it might be helpful to provide a pdf for the landing page you hit after clicking the confirm link. Here's that. 
[message_from_2016_confirmed.pdf](https://github.com/mattbaker/messagefrom2016/files/595474/message_from_2016_confirmed.pdf)

**Comment by ashanan** [comment]
In the interest of getting this up today (today!) I think we're going to leave it as is and revisit the confirmation page post release.

**Comment by deanarutherford** [comment]
Ok! Maybe I'll wait till that's changed to post it places? I just think it sends a bit of a mixed message to be like "Yay you're done! But here's this blank slate again?"  and I don't want to confuse people. Even just the sentence without the icon would be fine. 

But today! Woo!

**Comment by mattbaker** [comment]
@deanarutherford — do a full run through and see if the current solution works for you

**Comment by mattbaker** [comment]
Me and Deana chatted, sounds like this works
