### ISSUE TITLE
Fidelity pass

### ISSUE THREAD

**Issue by deanarutherford** [mattbaker/messagefrom2016#32]
Here's a couple really minor issues I found on the site! I'll post another one with mobile stuff.
[fidelity.pdf](https://github.com/mattbaker/messagefrom2016/files/595943/fidelity.pdf)

**Comment by deanarutherford** [comment]
Mobile: 
[fidelity_mobile.pdf](https://github.com/mattbaker/messagefrom2016/files/595965/fidelity_mobile.pdf)

**Comment by mattbaker** [comment]
Any guess on the header font sizes for mobile?

**Comment by deanarutherford** [comment]
I think figuring that out would take me a little longer than I have because I have to get to this book club thing, but I can find it out for real when I get home. Meanwhile, try like 36? That's probably small enough to fit it on one line

**Comment by mattbaker** [comment]
I believe I've addressed the desktop issues, closing this in favor of #34 (mobile fidelity pass)
