### ISSUE TITLE
Does it look ok on mobile?

### ISSUE THREAD

**Issue by mattbaker** [mattbaker/messagefrom2016#5]
We just need to double check that it's functional on mobile, doesn't need to be pretty.

**Comment by mattbaker** [comment]
Update: pretty awkward, after we get the design settled we'll need to take a pass.

**Comment by deanarutherford** [comment]
@mattbaker anything I can do to help?

**Comment by mattbaker** [comment]
I think I just fixed it!

**Comment by mattbaker** [comment]
Fixed in #3794929 (styling branch)
