### ISSUE TITLE
Meta tag copy and image needed

### ISSUE THREAD

**Issue by mattbaker** [mattbaker/messagefrom2016#8]
We need copy for the sharing metadata, and it would be nice to have an image. Even if that image was a simple american flag (B&W to match? No strong feelings here).

Here's the current meta data copy (see descriptions):

```
<!-- Facebook -->
    <meta property="og:url"                content="http://messagefrom2016.com" />
    <meta property="og:type"               content="website" />
    <meta property="og:title"              content="Message From 2016" />
    <meta property="og:description"        content="Write a letter to your future self, returned to you one month before mid-term elections." />
    <meta property="og:image"              content="http://static01.nyt.com/images/2015/02/19/arts/international/19iht-btnumbers19A/19iht-btnumbers19A-facebookJumbo-v2.jpg" />

    <!-- Twitter -->
    <meta name="twitter:card" content="summary" />
    <meta name="twitter:site" content="@messagefrom2016" />
    <meta name="twitter:title" content="Message From 2016" />
    <meta name="twitter:description" content="Write a letter to your future self, returned to you one month before mid-term elections." />
    <meta name="twitter:image" content="https://farm6.staticflickr.com/5510/14338202952_93595258ff_z.jpg" />
```

**Comment by deanarutherford** [comment]
So this is like the blurb that shows up when you post a link on facebook, or hover over the url, stuff like that? Is this a thing people rely on for actual information, or can it be cheeky? If it has to be straightforward, I think what you wrote is fine, though it could maybe be shorter.

A few cheeky options:

Using your despair for good.
Fighting apathy with despair.
Slap your future self in the face.
Hold your future self accountable.

**Comment by mattbaker** [comment]
I like that last one! The one I wrote was pure filler text. Maybe we should combine them, I'm picturing how this shows up in FB, we'd want to describe what you do on the site.

> Hold your future self accountable. Write a letter to yourself about your feelings following this election, it will be returned to you one month before mid-term elections.

It doesn't have to be one month prior, I just wanted to put something down, what do you think would be a good time?

**Comment by deanarutherford** [comment]
Maybe two months? 

Hold your future self accountable. Write down your hopes, fears, and feelings about this election and we'll throw them back in your face two months before the midterms.

That's probably too sassy....

**Comment by mattbaker** [comment]
Two months sounds good to me.

Perhaps a little too sassy ;)

What about this?

> Write down your hopes, fears, and feelings about this election and we'll send them back to you two months before the midterms. Don't become complacent, hold your future self accountable.

**Comment by deanarutherford** [comment]
I'd scrap the "don't become complacent" part and say we've got a deal

**Comment by mattbaker** [comment]
I dig it!

**Comment by mattbaker** [comment]
Closing in favor of #18 and #15
